version: "3.8"

services:
  bot:
    build: .
    container_name: kntu_bot25
    restart: unless-stopped
    env_file: .env
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - ./data.json:/app/data.json
